Repository PrestaShop/ps_categoryproducts, pull requests merged in 2023-02, with the labels that each got.

#36 Adapt `ps_categoryproducts` for multiples versions of PrestaShop
  .github/workflows/php.yml
  ps_categoryproducts.php
  tests/phpstan/phpstan-1.7.1.2.neon
  tests/phpstan/phpstan-1.7.2.5.neon
  tests/phpstan/phpstan-1.7.3.4.neon
  tests/phpstan/phpstan-1.7.4.4.neon
  tests/phpstan/phpstan-8.0.neon
Labels: enhancement, QA approved

#37 Bump version to 1.0.7
  config.xml
  ps_categoryproducts.php
Labels: enhancement

#38 Release 1.0.7
  .github/workflows/php.yml
  config.xml
  ps_categoryproducts.php
  tests/phpstan/phpstan-1.7.1.2.neon
  tests/phpstan/phpstan-1.7.2.5.neon
  tests/phpstan/phpstan-1.7.3.4.neon
  tests/phpstan/phpstan-1.7.4.4.neon
  tests/phpstan/phpstan-8.0.neon
Labels: QA approved
